delete from cities;

ALTER SEQUENCE cities_id_seq RESTART WITH 1;

INSERT INTO CITIES (NAME)
VALUES  ('Shanghai');

INSERT INTO CITIES (NAME)
VALUES  ('Beijing');

INSERT INTO CITIES (NAME)
VALUES  ('Mumbai');

INSERT INTO CITIES (NAME)
VALUES  ('Sydney');

INSERT INTO CITIES (NAME)
VALUES  ('Tokyo');

INSERT INTO CITIES (NAME)
VALUES  ('Moscow');

INSERT INTO CITIES (NAME)
VALUES  ('Hong Kong');

INSERT INTO CITIES (NAME)
VALUES  ('Bangkok');

INSERT INTO CITIES (NAME)
VALUES  ('London');

INSERT INTO CITIES (NAME)
VALUES  ('Paris');

INSERT INTO CITIES (NAME)
VALUES  ('New York');